@baseUrl = http://localhost:5000/api/auth


### LOGIN

POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "test04",
  "password": "Password123@"
}

> {%
    var setCookieHeader = response.headers.valueOf("Set-Cookie");
    
    if (setCookieHeader) {
        var match = setCookieHeader.match(/jwt=([^;]+)/);
        
        if (match) {
            client.env.set("nguyencodervn", match[1]);
            client.log("Đã trích xuất JWT thành công: " + match[1]);
        } else {
            client.log("Không tìm thấy cookie tên là jwt trong header!");
        }
    }
%}

### AUTH CHECK

# @no-cookie-jar 
GET {{baseUrl}}/authCheck HTTP/1.1
Cookie: jwt={{nguyencodervn}}
