### 

@baseUrl = http://localhost:5000/api/auth


### Registration

POST {{baseUrl}}/signup HTTP/1.1
Content-Type: application/json

{
  "email": "est04@example.com",
  "password": "password123@",
  "username": "est04"
}


### 

POST {{baseUrl}}/login HTTP/1.1

{
  "password": "password123",
  "username": "test01"
}


### FORM

POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=Test03&
password=Password123@


### 

# @attach-cookie-jar

POST {{baseUrl}}/logout HTTP/1.1

{}


### 

# @attach-cookie-jar

GET {{baseUrl}}/authCheck HTTP/1.1


### 

GET {{baseUrl}}/authCheck HTTP/1.1
Cookie: jwt={{FORM.response.cookies.jwt.value}}
